import test from 'node:test';
import assert from 'node:assert/strict';
import {createCompanyStore} from '../src/company/store.js';
import {COMPANY_METHOD} from '../src/company/method.js';
const binding = () => ({schema:'kn.company-source-binding.v0.1',repository:'GrazianoGuiducci/kernel-nautico',branch:'work/first',revision:'a'.repeat(40),sourceId:'kn:source:company-case:v1',sourceRevision:'b'.repeat(64),viewId:'kn:view:company-field:v1',assetPath:null,sources:[{path:'KERNEL.md',blob:'c'.repeat(40),sha256:'d'.repeat(64),revision:'a'.repeat(40),scope:'owner_source_snapshot'}],contextDigest:'b'.repeat(64),observation:'local_build_snapshot',freshness:'pinned_not_continuous_remote',availability:'available'});
const input=()=>({label:'Illustrative supplier case',originalContribution:'Source identity remains explicit.',contextId:'rete',company:'',project:'',object:'',definitions:[],sourceRefs:[],questions:[],linkedDesign:null});
async function specimen(){let source=binding();const store=await createCompanyStore({getSourceBinding:()=>source,storage:null});store.capture(input());return {store,set:value=>{source=value;}};}
test('branch locator alone preserves applicable case, exact request and historical bytes',async()=>{const {store,set}=await specimen();const request=await store.prepareRequest(COMPANY_METHOD);const before=store.exportState();set({...binding(),branch:'work/second'});assert.equal(store.snapshot().sourceStatus.state,'current');assert.equal(store.exportState(),before);assert.deepEqual(await store.prepareRequest(COMPANY_METHOD),request);assert.equal(store.snapshot().case.invalidations.length,0);});
test('no-op revision across a locator change does not allocate another event',async()=>{const {store,set}=await specimen();const before=store.exportState();set({...binding(),branch:'work/second'});store.revise(input());assert.equal(store.exportState(),before);});
test('different work on a new branch retains the original and records the new locator',async()=>{const {store,set}=await specimen();set({...binding(),branch:'work/second'});store.revise({...input(),questions:['Which source qualifies the installed revision?']});const s=store.snapshot();assert.equal(s.case.revisions.length,2);assert.equal(s.case.revisions[0].sourceBinding.branch,'work/first');assert.equal(s.revision.sourceBinding.branch,'work/second');assert.equal(s.sourceStatus.state,'current');});
test('a material source change remains sticky even if the original bytes and locator return',async()=>{const {store,set}=await specimen();const changed=binding();changed.sources[0].blob='f'.repeat(40);set(changed);assert.equal(store.snapshot().sourceStatus.state,'stale');set({...binding(),branch:'work/other'});assert.equal(store.snapshot().sourceStatus.state,'stale');await assert.rejects(store.prepareRequest(COMPANY_METHOD));const serialized=store.exportState();const receiver=await createCompanyStore({getSourceBinding:binding,storage:null});await receiver.importState(serialized);assert.equal(receiver.snapshot().sourceStatus.state,'stale');});
test('unavailable source is not made usable by a changed locator',async()=>{const {store,set}=await specimen();set({...binding(),branch:'work/second',availability:'unavailable'});assert.equal(store.snapshot().sourceStatus.state,'unavailable');await assert.rejects(store.prepareRequest(COMPANY_METHOD));});
test('fresh receiving store preserves a branch-only transferred case byte for byte',async()=>{const {store}=await specimen();await store.prepareRequest(COMPANY_METHOD);const bytes=store.exportState();const receiver=await createCompanyStore({getSourceBinding:()=>({...binding(),branch:'work/new-receiver'}),storage:null});await receiver.importState(bytes);assert.equal(receiver.exportState(),bytes);assert.equal(receiver.snapshot().sourceStatus.state,'current');});
