"""Exercise real browser input convergence, not hand-authored event fixtures."""
import json, os, pathlib, platform
from importlib.metadata import version
from playwright.sync_api import sync_playwright
OUT=pathlib.Path(os.environ.get('KN_EVIDENCE','evidence'));OUT.mkdir(parents=True,exist_ok=True)
URL='http://127.0.0.1:8876/'
checks=[];errors=[];external=[];snapshots={};browser_version=None
ANCHOR='kn:anchor:stern-access'
def check(name,value,detail=None):
    checks.append(dict(name=name,passed=bool(value),detail=detail))
    if not value:raise AssertionError(f'{name}: {detail}')
def settle(page):
    page.evaluate('() => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)))')
def snap(page):return page.evaluate('window.KN_FOCUS.snapshot()')
def debug(page):return page.evaluate('window.__KN_DEBUG__.snapshot()')
def ready(page):
    page.wait_for_function('window.__KN_DEBUG__?.ready && window.KN_FOCUS',timeout=90000);settle(page)
def command(page,text,voice=False):
    page.locator('#focus-voice').set_checked(voice)
    page.locator('#focus-input').fill(text);page.locator('#focus-input').press('Enter');settle(page)
def events(page):
    page.on('pageerror',lambda e: errors.append(str(e)))
    page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
    page.on('request',lambda r:external.append(r.url) if not r.url.startswith(URL) and not r.url.startswith('data:') else None)
try:
    with sync_playwright() as p:
        browser=p.chromium.launch(headless=True,executable_path=os.environ.get('KN_CHROMIUM_PATH') or None,
            args=['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'])
        browser_version=browser.version
        ctx=browser.new_context(viewport=dict(width=1440,height=900))
        page=ctx.new_page();events(page)
        page.goto(URL+'?test=1',wait_until='networkidle');ready(page)
        root=debug(page)['uuid'];check('primary_carrier_is_webgl',not debug(page)['fallback'])
        check('context_panel_starts_closed',not page.locator('#focus-panel').is_visible())
        page.evaluate("document.addEventListener('kn:focus', e => { window.lastFocusEvent = e.detail; })")
        for act in ['FORM','BUILD','LIVE','RETURN']:
            page.locator(f'[data-act="{act}"]').click();settle(page)
            f=snap(page);check('address_'+act,f['field']['address']['semantic_id']=='kn:phase:'+act)
            check('phase_state_'+act,f['field']['state']['presentation_act']==act)
            check('phase_pointer_'+act,f['event']['modality']=='pointer')
            check('preserved_yacht_'+act,debug(page)['uuid']==root)
        expected=snap(page)['field'];snapshots['return_pointer']=snap(page)
        page.locator('#focus-toggle').click();settle(page)
        check('open_retains_target',snap(page)['field']==expected)
        command(page,'mostrami RETURN');check('return_text_parity',snap(page)['field']==expected)
        check('return_text_provenance',snap(page)['event']['modality']=='text')
        command(page,'mostrami RETURN',True);check('return_simulated_voice_parity',snap(page)['field']==expected)
        check('voice_is_marked_simulated',snap(page)['event']['modality']=='voice_simulated')
        snapshots['return_voice']=snap(page)
        page.screenshot(path=str(OUT/'FOCUS_RETURN.png'))
        before=snap(page)
        command(page,'FORM o RETURN');check('ambiguous_does_not_move',snap(page)==before)
        command(page,'paratia 17');check('unrepresented_part_not_invented',snap(page)==before)
        command(page,'calcola rotta per Ancona');check('route_horizon_not_executed',snap(page)==before)
        command(page,'<script>window.injected=true</script>');check('text_not_executable',not page.evaluate('Boolean(window.injected)'))
        check('invalid_does_not_move',snap(page)==before)
        page.locator('#focus-close').click();settle(page)
        check('close_restores_invoker',page.locator('#focus-toggle').evaluate('(e)=>document.activeElement===e'))
        page.locator('#focus-anchor').click();settle(page)
        expected=snap(page)['field'];snapshots['anchor_pointer']=snap(page)
        check('spatial_address',expected['address']['semantic_id']==ANCHOR)
        check('source_anchor_matches',expected['state']['spatial_anchor']=='stern-access')
        a=page.locator('#focus-anchor').bounding_box();source=debug(page)['relationEndpoints']['source']
        check('hit_target_on_visible_source',abs(a['x']+a['width']/2-source['x'])<2 and abs(a['y']+a['height']/2-source['y'])<2)
        command(page,'mostrami accesso a poppa');check('anchor_text_parity',snap(page)['field']==expected)
        command(page,'accesso a poppa',True);check('anchor_voice_parity',snap(page)['field']==expected)
        snapshots['anchor_voice']=snap(page)
        page.screenshot(path=str(OUT/'FOCUS_ANCHOR.png'))
        command(page,'cosa manca qui');check('contextual_question_preserves_identity',snap(page)['field']==expected)
        check('gaps_visible',page.locator('#focus-gaps').evaluate('(e)=>e.open'))
        check('sources_pinned_not_loaded',all(s['read_state']=='linked_not_loaded' and s['freshness']=='pinned_reference_not_live' for s in snap(page)['field']['knowledge']['sources']))
        check('machine_state_equals_event',page.evaluate('JSON.stringify(window.lastFocusEvent)===JSON.stringify(window.KN_FOCUS.snapshot())'))
        page.evaluate('window.KN_FOCUS.snapshot().field.capabilities.execute=true')
        check('export_cannot_mutate_authority',snap(page)['field']['capabilities']['execute'] is False)
        page.evaluate("window.__KN_DEBUG__.seekAct('BUILD')");settle(page)
        check('spatial_focus_survives_timeline',snap(page)['field']['address']['semantic_id']==ANCHOR)
        check('context_refreshes_on_phase_change',snap(page)['field']['state']['presentation_act']=='BUILD')
        check('visible_explanation_follows_phase',page.locator('#focus-explanation').inner_text()==snap(page)['field']['state']['current_resultant'])
        check('illustrative_status_visible',page.locator('#focus-reality').is_visible() and 'illustrativo' in page.locator('#focus-reality').inner_text())
        page.locator('#focus-close').click();settle(page)
        check('anchor_invoker_restored',page.locator('#focus-anchor').evaluate('(e)=>document.activeElement===e'))
        page.locator('[data-act="RETURN"]').focus();page.keyboard.press('Enter');settle(page)
        check('keyboard_same_address',snap(page)['field']['address']['semantic_id']=='kn:phase:RETURN')
        check('keyboard_provenance',snap(page)['event']['modality']=='keyboard')
        page.evaluate("window.KN_FOCUS.select('kn:anchor:stern-access')");settle(page)
        check('machine_input_selects_same_target',snap(page)['field']['address']['semantic_id']==ANCHOR)
        check('read_only_capabilities',all(snap(page)['field']['capabilities'][k] is False for k in ['execute','edit_project','approve','microphone','ai_connected','route_planning']))
        page.locator('#focus-close').click();settle(page)
        page.locator('#play').click();page.wait_for_timeout(300);settle(page)
        check('prior_play_control_still_operates',debug(page)['playing'])
        page.locator('#play').click();settle(page)
        ctx.close()
        mobile=browser.new_context(viewport=dict(width=390,height=844),has_touch=True,is_mobile=True)
        mp=mobile.new_page();events(mp);mp.goto(URL+'?test=1',wait_until='networkidle');ready(mp)
        mp.locator('[data-act="RETURN"]').tap();settle(mp)
        expected=snap(mp)['field'];snapshots['return_touch']=snap(mp)
        check('actual_emulated_touch_event',snap(mp)['event']['modality']=='touch')
        check('touch_same_return_as_desktop',expected==snapshots['return_pointer']['field'])
        mp.locator('#focus-toggle').tap();settle(mp)
        command(mp,'mostrami RETURN',True);check('touch_voice_return_parity',snap(mp)['field']==expected)
        mp.screenshot(path=str(OUT/'FOCUS_MOBILE_RETURN.png'))
        panel=mp.locator('#focus-panel').bounding_box();footer=mp.locator('footer').bounding_box()
        check('mobile_panel_keeps_navigation_available',panel['y']+panel['height']<=footer['y'])
        check('mobile_panel_in_viewport',panel['x']>=0 and panel['x']+panel['width']<=390)
        mp.locator('#focus-close').tap();settle(mp)
        mp.locator('#focus-anchor').tap();settle(mp)
        expected=snap(mp)['field'];check('spatial_touch_target',expected['address']['semantic_id']==ANCHOR)
        check('spatial_touch_provenance',snap(mp)['event']['modality']=='touch')
        command(mp,'accesso a poppa',True);check('touch_voice_anchor_parity',snap(mp)['field']==expected)
        check('mobile_scope_visible',mp.locator('#focus-reality').is_visible() and 'non dati di bordo' in mp.locator('#focus-reality').inner_text())
        mp.screenshot(path=str(OUT/'FOCUS_MOBILE_ANCHOR.png'));snapshots['anchor_touch']=snap(mp)
        mobile.close()
        reduced=browser.new_context(viewport=dict(width=1024,height=768),reduced_motion='reduce')
        rp=reduced.new_page();events(rp);rp.goto(URL+'?test=1',wait_until='networkidle');ready(rp)
        rp.locator('#focus-anchor').click();settle(rp)
        check('reduced_motion_target_resolves',snap(rp)['field']['address']['semantic_id']==ANCHOR and not debug(rp)['playing'])
        rp.screenshot(path=str(OUT/'FOCUS_REDUCED_ANCHOR.png'));reduced.close()
        static=browser.new_context(viewport=dict(width=390,height=844),has_touch=True)
        sp=static.new_page();events(sp);sp.goto(URL+'?test=1&static=1',wait_until='networkidle');ready(sp)
        sp.locator('[data-act="RETURN"]').tap();settle(sp)
        sp.locator('#focus-anchor').tap();settle(sp)
        f=snap(sp)['field'];check('fallback_preserves_address',f['address']==snapshots['anchor_touch']['field']['address'])
        check('fallback_does_not_inherit_geometry',f['state']['geometry']=='schematic_alternative')
        check('fallback_substitution_is_explicit',sp.locator('#focus-reality').is_visible() and 'schema alternativo' in sp.locator('#focus-reality').inner_text())
        a=sp.locator('#focus-anchor').bounding_box();target=sp.locator('#fallback circle').bounding_box()
        check('fallback_hit_target_bound_to_real_svg',abs(a['x']+a['width']/2-target['x']-target['width']/2)<2 and abs(a['y']+a['height']/2-target['y']-target['height']/2)<2)
        command(sp,'accesso a poppa',True);check('fallback_voice_parity',snap(sp)['field']==f)
        sp.screenshot(path=str(OUT/'FOCUS_STATIC_ANCHOR.png'));snapshots['static_anchor']=snap(sp)
        static.close()
        check('no_external_runtime_request',external==[],external)
        check('no_browser_errors',errors==[],errors)
        browser.close()
finally:
    (OUT/'focus-browser-evidence.json').write_text(json.dumps(dict(
        runtime_commit=os.environ.get('GITHUB_SHA'),checks=checks,snapshots=snapshots,
        errors=errors,external_requests=external,chromium=browser_version,playwright=version('playwright'),platform=platform.platform(),
        voice='simulated_transcript_only',touch='browser_emulation_not_real_device',source_loading='pinned_links_not_live_document_retrieval'),indent=2,ensure_ascii=False))
print(f'{len(checks)}/{len(checks)} semantic focus browser checks passed')
