import { SUBJECT, OBJECTS, KINDS, CONTEXTS, CONTEXT_IDS, SOURCE_LINKS, objectById, contextById, visibleRelations, relatedContexts } from './field.mjs';
import { createReadingController, comparisonRows, receivingStatus, validateBookmark } from './model.mjs';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const yacht=(x=500,y=280,scale=1,rotate=0)=>`<g transform="translate(${x} ${y}) rotate(${rotate}) scale(${scale})" class="yacht"><path class="hull-fill" d="M-285-84Q-90-142 142-98Q238-77 295 0Q238 77 142 98Q-90 142-285 84Z"/><path d="M-267-66Q-72-119 134-81Q218-59 271 0Q218 59 134 81Q-72 119-267 66Z"/><path d="M-275-47H-185V47H-275M-160-57H20V57H-160ZM40-61L148-43 195 0 148 43H40ZM-88-57V57M4-57V57M-270 0H268"/><path class="fine" d="M-231-65V65M-204-70V70M-143-74H5M-143 74H5M63-28H133L166 0 133 28H63Z"/><path class="hot-zone" d="M-285-83H-177V83H-285Z"/></g>`;
const grid=`<defs><pattern id="cvs-grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" fill="none" stroke="currentColor" stroke-width=".5"/></pattern><radialGradient id="cvs-glow"><stop stop-color="#31566a" stop-opacity=".46"/><stop offset="1" stop-color="#0c1c27" stop-opacity="0"/></radialGradient></defs><rect width="1000" height="540" fill="url(#cvs-grid)" opacity=".22"/><ellipse cx="500" cy="290" rx="470" ry="250" fill="url(#cvs-glow)"/>`;
function motif(kind){
 if(kind==='layers')return `<g opacity=".22">${yacht(500,326,.82,-15)}${yacht(500,350,.82,-15)}</g>${yacht(500,290,.82,-15)}<path class="dimension" d="M205 163L720 30M248 446L795 305"/>`;
 if(kind==='assembly')return `${yacht(500,245,.96,0)}<g class="construction"><path d="M320 120V375M420 120V375M520 120V375M620 120V375M720 120V375M214 355H785"/></g><rect class="candidate-part" x="620" y="205" width="82" height="74" rx="8"/><rect class="reference-part" x="300" y="205" width="82" height="74" rx="8"/>`;
 if(kind==='network')return `<circle class="ring" cx="470" cy="265" r="116"/><circle class="ring fine" cx="470" cy="265" r="150"/>${yacht(652,462,.27,-14)}`;
 if(kind==='experience')return `<path class="wake" d="M35 350Q300 290 520 350T965 350M40 378Q300 318 520 378T965 378"/>${yacht(498,292,.9,-8)}<path class="dimension" d="M500 30V477"/>`;
 if(kind==='scales')return `<circle class="ring" cx="250" cy="270" r="183"/>${yacht(250,270,.45,-70)}<path class="dimension" d="M500 70V480"/><g class="chart"><path d="M554 107Q690 50 843 108T968 165M550 148Q669 100 816 157T960 207M550 369Q658 324 827 398T964 420M578 205Q647 173 664 220T714 240Q789 187 867 280T954 322"/><path class="candidate-part" d="M588 344L686 301 743 331 821 263 910 238"/><circle cx="686" cy="301" r="8"/><circle cx="821" cy="263" r="8"/></g>`;
 return `<path class="time-axis" d="M120 119H830Q911 119 911 200V290Q911 386 825 389H139"/><path class="return-path" d="M830 441Q490 557 140 444"/><g class="fine">${yacht(490,272,.38,0)}</g>`;
}
function artwork(contextId){const c=contextById(contextId);const relations=visibleRelations(contextId);
 const edges=relations.map(r=>{const a=c.nodes.find(n=>n.id===r.from),b=c.nodes.find(n=>n.id===r.to);return `<path class="relation ${r.predicate==='unknown_correspondence'?'uncertain':''}" data-from="${esc(r.from)}" data-to="${esc(r.to)}" d="M${a.x*10} ${a.y*5.4}Q${(a.x+b.x)*5} ${a.y*5.4} ${b.x*10} ${b.y*5.4}"/>`;}).join('');
 return `<svg class="cvs-art" viewBox="0 0 1000 540" preserveAspectRatio="none" aria-hidden="true" focusable="false">${grid}${motif(c.morphology)}<g class="relations">${edges}</g></svg>`;}
const mini=kind=>`<svg viewBox="0 0 1000 540" aria-hidden="true" focusable="false">${motif(kind)}</svg>`;
const sourceBase='./public-receiver/sources/';
export function mountContextualSurface(root,{controller=createReadingController(),onAsk=null,onOpenCase=null,embedded=false}={}){
 if(!(root instanceof HTMLElement))throw new TypeError('Serve un contenitore HTML.');
 root.classList.add('cvs-app');root.dataset.embedded=String(embedded);
 root.innerHTML=`<a class="cvs-skip" href="#cvs-field-title">Vai alla vista di lavoro</a>
 <header class="cvs-brand"><div>KERNEL <span>NAUTICO</span><small>Rappresentazioni del lavoro</small></div><p>PROTOTIPO DI INTERAZIONE<br><span>Studio locale · nessun sistema aziendale collegato</span></p></header>
 <nav class="cvs-context-nav" aria-label="Contesti di lavoro"><button type="button" data-context="overview" aria-current="page">Panoramica</button>${CONTEXT_IDS.map(id=>`<button type="button" data-context="${id}">${esc(CONTEXTS[id].label)}</button>`).join('')}</nav>
 <section class="cvs-thread" aria-label="Questione che continua tra le viste"><div><span class="cvs-overline">OGGETTO DELLA DOMANDA</span><strong>${esc(SUBJECT.label)}</strong><span class="cvs-scenario">${esc(SUBJECT.scenario)}</span></div><div class="cvs-thread-actions"><span id="cvs-selected-label">Nessun elemento selezionato</span><button type="button" id="cvs-back" disabled aria-label="Torna alla lettura precedente">← Indietro</button></div></section>
 <main class="cvs-main"><section class="cvs-work"><div class="cvs-view-heading"><div><p id="cvs-eyebrow" class="cvs-overline"></p><h1 id="cvs-field-title" tabindex="-1"></h1><p id="cvs-lead"></p></div><div class="cvs-mode" role="group" aria-label="Modo di lettura"><button type="button" data-mode="map" aria-pressed="true">Mappa</button><button type="button" data-mode="list" aria-pressed="false">Elenco</button></div></div>
 <div id="cvs-overview" class="cvs-overview"></div><div id="cvs-field" class="cvs-field" hidden><div class="cvs-map" id="cvs-map"></div><div id="cvs-linear" class="cvs-linear" hidden></div></div>
 <p id="cvs-caption" class="cvs-caption"></p><details id="cvs-relations" class="cvs-relations"><summary>Leggi le relazioni della vista</summary><div id="cvs-relations-body"></div></details>
 <section class="cvs-compare" id="cvs-compare" hidden aria-labelledby="cvs-compare-title"><div><p class="cvs-overline">CONFRONTO · NON DECISIONE</p><h2 id="cvs-compare-title" tabindex="-1">A e B restano oggetti diversi.</h2></div><div class="cvs-table-wrap"><table><caption class="cvs-sr">Confronto fra componente A e alternativa B nello scenario illustrativo</caption><thead><tr><th>Relazione</th><th>Riferimento A</th><th>Alternativa B</th></tr></thead><tbody>${comparisonRows().map(r=>`<tr>${r.map((s,i)=>`<${i?'td':'th'}${i?'':' scope="row"'}>${esc(s)}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div><p>Questo confronto non modifica progetto, distinta o configurazione a bordo.</p></section>
 </section><aside class="cvs-inspector" aria-labelledby="cvs-inspector-title"><p class="cvs-overline">LEGGERE E PROSEGUIRE</p><div id="cvs-inspector-content"></div><button type="button" id="cvs-return-selection" hidden>← Torna alla selezione</button><div class="cvs-inspector-actions"><button type="button" id="cvs-compare-toggle" aria-pressed="false">Confronta A e B</button><button type="button" id="cvs-ask" class="cvs-primary">Prepara una domanda ↗</button><button type="button" id="cvs-open-case">Apri il caso esistente ↗</button><p id="cvs-case-note"></p></div>
 <details class="cvs-question"><summary>La domanda che stai seguendo</summary><label for="cvs-question-input">Puoi cambiarla senza cambiare i dati dello scenario.</label><textarea id="cvs-question-input" rows="3" maxlength="1200"></textarea><small>Resta in memoria in questa pagina. Non entra nel segnalibro né viene inviata alla chat.</small></details></aside></main>
 <section class="cvs-continuation"><div><p class="cvs-overline">SEGUI LA STESSA ALTERNATIVA</p><p>Una proposta del fornitore cambia le domande per cantiere e assistenza.</p></div><div class="cvs-guided" role="group" aria-label="Esempio di lettura trasversale, non workflow"><button type="button" data-follow="rete">1 · La proposta</button><span aria-hidden="true">→</span><button type="button" data-follow="cantiere">2 · La realizzazione</button><span aria-hidden="true">→</span><button type="button" data-follow="service">3 · La configurazione</button></div><small>Passaggi di lettura, non avanzamenti del lavoro aziendale.</small></section>
 <footer class="cvs-footer"><details><summary>Fonti, metodo e limiti</summary><p>CVS-01 è un esempio progettuale nuovo: non rappresenta un caso aziendale reale, un dato di bordo o una prova dell’apprendimento di un modello. Le mappe applicano le relazioni delle sorgenti Nautico; le geometrie e il caso illustrativo sono scelte di questo studio.</p><ul>${SOURCE_LINKS.map(([title,path])=>`<li><a href="${sourceBase+path}" target="_blank" rel="noopener noreferrer">${esc(title)} ↗</a></li>`).join('')}</ul><p>Mappe e lettura lineare usano gli stessi oggetti. Nessun dato viene salvato automaticamente o inviato a un servizio. L’integrazione con la MAIOS Chat reale e la pubblicazione restano distinte.</p></details><div><button type="button" id="cvs-export">Esporta la lettura</button><button type="button" id="cvs-import">Riprendi la lettura</button><input type="file" id="cvs-file" accept=".json,application/json" hidden></div></footer>
 <p id="cvs-status" class="cvs-status" role="status" aria-live="polite"></p>
 <dialog id="cvs-prompt" aria-labelledby="cvs-prompt-title"><div class="cvs-dialog-heading"><p class="cvs-overline">PASSAGGIO ALLA CONVERSAZIONE</p><button type="button" id="cvs-dialog-close" aria-label="Chiudi la domanda">Chiudi ×</button></div><h2 id="cvs-prompt-title">La vista prepara il contesto, non la risposta.</h2><p>Questa domanda usa soltanto le etichette pubbliche dello scenario. Non include la tua domanda privata o dati del caso.</p><label for="cvs-prompt-text">Testo da consegnare alla chat</label><textarea id="cvs-prompt-text" rows="5" readonly></textarea><div class="cvs-dialog-actions"><button type="button" id="cvs-copy" class="cvs-primary">Copia la domanda</button><button type="button" id="cvs-send-to-composer">Apri nel compositore MAIOS</button></div><p id="cvs-prompt-note" role="status"></p></dialog>`;
 const $=id=>root.querySelector('#'+id);const narrow=matchMedia('(max-width: 700px)');let mode=narrow.matches?'list':'map',manualMode=false,previous=null,disposed=false;
 let navigationHandler=null, navigationBusy=false, selectionOrigin=null;
 const singlePane=()=>matchMedia('(max-width: 950px)').matches;
 function focusVisible(element){element?.focus({preventScroll:true});element?.scrollIntoView({block:'nearest',behavior:'instant'});}
 const report=text=>{$('cvs-status').textContent=text;};
 const setMode=next=>{mode=next;for(const b of root.querySelectorAll('[data-mode]'))b.setAttribute('aria-pressed',String(b.dataset.mode===mode));$('cvs-map').hidden=mode!=='map';$('cvs-linear').hidden=mode!=='list';};
 function overview(){return CONTEXT_IDS.map((id,i)=>{const c=CONTEXTS[id];return `<button type="button" data-context="${id}" class="cvs-overview-item"><span class="cvs-mini">${mini(c.morphology)}</span><span class="cvs-overline">0${i+1} · ${esc(c.short)}</span><strong>${esc(c.label)}</strong><span>${esc(c.question)}</span><span class="cvs-entry">Esplora questa prospettiva ↗</span></button>`;}).join('');}
 function drawContext(id){const c=CONTEXTS[id];$('cvs-map').innerHTML=artwork(id)+c.nodes.map(n=>{const o=OBJECTS[n.id];return `<button type="button" class="cvs-node" data-object="${n.id}" style="--x:${n.x}%;--y:${n.y}%" aria-pressed="false"><span>${esc(KINDS[o.kind])}</span><strong>${esc(o.label)}</strong></button>`;}).join('');
  $('cvs-linear').innerHTML=c.nodes.map(n=>{const o=OBJECTS[n.id];return `<button type="button" class="cvs-linear-node" data-object="${n.id}" aria-pressed="false"><span class="cvs-overline">${esc(KINDS[o.kind])}</span><strong>${esc(o.label)}</strong><span>${esc(o.state)}</span></button>`;}).join('');
  $('cvs-relations-body').innerHTML=visibleRelations(id).map(r=>`<p><strong>${esc(OBJECTS[r.from].label)}</strong> <span>${esc(r.label)}</span> <strong>${esc(OBJECTS[r.to].label)}</strong><br><small>${esc(r.meaning)}</small></p>`).join('');
 }
 function render(s){if(disposed)return;const changedContext=!previous||previous.contextId!==s.contextId;const changedSelection=!previous||previous.selectedId!==s.selectedId;
  const c=contextById(s.contextId),o=objectById(s.selectedId);
  if(changedContext){
   $('cvs-eyebrow').textContent=c?`${c.label.toUpperCase()} · ${c.short.toUpperCase()}`:'UNA QUESTIONE · SEI PROSPETTIVE';
   $('cvs-field-title').textContent=c?c.title:'Segui una scelta attraverso il lavoro dell’azienda.';
   $('cvs-lead').textContent=c?c.explanation:'Scegli da dove guardare l’accesso di poppa. Le rappresentazioni cambiano; la domanda e le identità che la riguardano possono continuare.';
   $('cvs-overview').hidden=Boolean(c);$('cvs-field').hidden=!c;$('cvs-relations').hidden=!c;root.querySelector('.cvs-mode').hidden=!c;
   if(c)drawContext(s.contextId);else $('cvs-overview').innerHTML=overview();
   $('cvs-caption').textContent=c?c.takeAway:'Non è un organigramma né una sequenza obbligata. Ogni vista fa emergere relazioni diverse dello stesso campo.';
   for(const b of root.querySelectorAll('.cvs-context-nav [data-context]')){if(b.dataset.context===s.contextId)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}
   setMode(mode);
  }
  for(const b of root.querySelectorAll('[data-object]'))b.setAttribute('aria-pressed',String(b.dataset.object===s.selectedId));
  for(const p of root.querySelectorAll('.relation'))p.classList.toggle('selected',p.dataset.from===s.selectedId||p.dataset.to===s.selectedId);
  $('cvs-selected-label').textContent=o?`${o.label} · ${o.state}`:'Nessun elemento selezionato';$('cvs-back').disabled=!s.history.length;
  if(changedContext||changedSelection){
   const meaning=o?o.meaning:'Entra da un contesto, seleziona un elemento e osserva che cosa rimane uguale e che cosa cambia passando a un’altra vista.';
   const destinations=o?relatedContexts(o.id).filter(id=>id!==s.contextId):[];
   $('cvs-inspector-content').innerHTML=`<h2 id="cvs-inspector-title" tabindex="-1">${esc(o?o.label:'Lo stesso lavoro, senza perdere il filo.')}</h2><p class="cvs-state">${esc(o?o.state:'Orientamento')}</p><p>${esc(meaning)}</p>${o?`<p class="cvs-continuity-note">${esc(receivingStatus(o.id,s.contextId))}</p><dl><dt>Chi deve partecipare</dt><dd>${esc(o.owner)}</dd><dt>Passaggio utile</dt><dd>${esc(o.next)}</dd><dt>Provenienza</dt><dd>${esc(o.source)}</dd></dl>`:`<dl><dt>Che cosa puoi fare qui</dt><dd>Leggere, selezionare, confrontare e preparare una domanda.</dd><dt>Che cosa non cambia</dt><dd>Nessuna decisione, installazione o fonte aziendale viene modificata.</dd></dl>`}${destinations.length?`<div class="cvs-related"><p class="cvs-overline">CONTINUA LA SELEZIONE IN</p>${destinations.map(id=>`<button type="button" data-context="${id}">${esc(CONTEXTS[id].label)} ↗</button>`).join('')}</div>`:''}${c?`<details class="cvs-context-depth"><summary>Persone e fonti di questo contesto</summary><p>${esc(c.participants)}</p><p>${esc(c.system)}</p></details>`:''}`;
  }
  $('cvs-compare').hidden=!s.compare;$('cvs-compare-toggle').setAttribute('aria-pressed',String(s.compare));
  if(document.activeElement!==$('cvs-question-input'))$('cvs-question-input').value=s.question;
  if(previous&&(changedContext||changedSelection))report(`${c?c.label:'Panoramica'}. ${o?`${o.label}: ${o.state}.`:''} ${!s.represented?'La selezione non è disegnata in questa vista ma resta conservata.':''}`);
  previous=s;
 }
 const unsubscribe=controller.subscribe(render);render(controller.snapshot());
 $('cvs-open-case').disabled=typeof onOpenCase!=='function';$('cvs-case-note').textContent=onOpenCase?'Il caso continua nel suo spazio: la mappa non ne crea una copia.':'Questo studio non apre un nuovo caso. Il collegamento al caso esistente è predisposto per l’app Nautico.';
 $('cvs-send-to-composer').disabled=typeof onAsk!=='function';
 async function qualifyNavigation(id){if(navigationHandler){const receipt=await navigationHandler(id);if(receipt?.contextId!==id)throw new Error('Vista non confermata dal contesto ospite.');}}
 async function navigate(id){if(navigationBusy)return;navigationBusy=true;try{await qualifyNavigation(id);return controller.navigate(id);}finally{navigationBusy=false;}}
 async function click(e){const b=e.target.closest('button');if(!b||!root.contains(b))return;
  try{
   if(b.dataset.context){const wasInside=Boolean(b.closest('.cvs-inspector,.cvs-overview'));await navigate(b.dataset.context);if(wasInside)focusVisible($('cvs-field-title'));}
   if(b.dataset.object){selectionOrigin={id:b.dataset.object,mode};controller.select(b.dataset.object);$('cvs-return-selection').hidden=!singlePane();if(singlePane())focusVisible($('cvs-inspector-title'));}
   if(b.dataset.mode){manualMode=true;setMode(b.dataset.mode);report(mode==='list'?'Lettura lineare: stessi oggetti e relazioni.':'Mappa: stessa selezione e stessa domanda.');}
   if(b.dataset.follow){controller.select('part-b');await navigate(b.dataset.follow);focusVisible($('cvs-field-title'));}
  }catch(error){report(error.message);}
 }
 root.addEventListener('click',click);
 $('cvs-back').onclick=async()=>{if(navigationBusy)return;navigationBusy=true;try{const s=controller.snapshot(),target=s.history.at(-1);if(!target)return;if(target.contextId!==s.contextId)await qualifyNavigation(target.contextId);controller.back();if(s.contextId!==controller.snapshot().contextId)focusVisible($('cvs-field-title'));}catch(error){report(error.message);}finally{navigationBusy=false;}};
 $('cvs-return-selection').onclick=()=>{const container=mode==='list'?'cvs-linear':'cvs-map';const selected=selectionOrigin&&$(container).querySelector(`[data-object="${selectionOrigin.id}"]`);focusVisible(selected||$('cvs-field-title'));};
 $('cvs-compare-toggle').onclick=()=>{controller.compare(!controller.snapshot().compare);if(controller.snapshot().compare&&singlePane())focusVisible($('cvs-compare-title'));};
 $('cvs-question-input').oninput=e=>{try{controller.question(e.target.value);}catch(error){report(error.message);}};
 $('cvs-open-case').onclick=async()=>{if(onOpenCase)try{await onOpenCase();}catch{report('Lo spazio del caso non è stato raggiunto. La lettura resta disponibile.');}};
 $('cvs-ask').onclick=()=>{$('cvs-prompt-text').value=controller.publicPrompt();$('cvs-prompt-note').textContent=onAsk?'L’apertura nel compositore non invia la domanda.':'MAIOS Chat non è connessa in questo prototipo. Copia il testo per usarlo nel tuo assistente.';$('cvs-prompt').showModal();};
 $('cvs-dialog-close').onclick=()=>$('cvs-prompt').close();
 $('cvs-prompt').addEventListener('keydown',e=>{if(e.key==='Escape')e.stopPropagation();});
 $('cvs-prompt').addEventListener('close',()=>$('cvs-ask').focus({preventScroll:true}));
 $('cvs-copy').onclick=async()=>{try{await navigator.clipboard.writeText($('cvs-prompt-text').value);$('cvs-prompt-note').textContent='Domanda copiata. Non è stata inviata.';}catch{$('cvs-prompt-text').focus();$('cvs-prompt-text').select();$('cvs-prompt-note').textContent='Testo selezionato: usa il comando Copia del browser.';}};
 $('cvs-send-to-composer').onclick=async()=>{if(!onAsk)return;try{const text=$('cvs-prompt-text').value;const receipt=await onAsk({text,context:controller.publicContext(),effect:'draft_only'});if(receipt?.state!=='draft_visible'||receipt?.text!==text)throw new Error('Bozza non osservata.');$('cvs-prompt-note').textContent='Bozza visibile nel compositore. La domanda non è stata inviata.';}catch(error){$('cvs-prompt-note').textContent='Compositore non raggiunto. Il testo resta disponibile da copiare.';}};
 $('cvs-export').onclick=()=>{const blob=new Blob([JSON.stringify(controller.bookmark(),null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='kernel-nautico-lettura.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);report('Segnalibro di lettura preparato: nessuna domanda privata o dato del caso nel file.');};
 $('cvs-import').onclick=()=>$('cvs-file').click();
 $('cvs-file').onchange=async()=>{const file=$('cvs-file').files[0];if(!file)return;try{if(file.size>24000)throw new Error('File troppo grande per un segnalibro di lettura.');const bookmark=validateBookmark(await file.text());await qualifyNavigation(bookmark.view.contextId);controller.restore(bookmark);report('Lettura ripresa. Le fonti dello scenario non sono state modificate.');}catch(error){report(error.message);}finally{$('cvs-file').value='';}};
 const resize=e=>{if(!manualMode)setMode(e.matches?'list':'map');};narrow.addEventListener('change',resize);
 return Object.freeze({controller,render,openContext:navigate,observeContext(id){controller.navigate(id);return controller.snapshot();},setNavigationHandler(fn){if(fn!==null&&typeof fn!=='function')throw new TypeError('Handler non riconosciuto.');navigationHandler=fn;},publicContext:()=>controller.publicContext(),destroy(){disposed=true;unsubscribe();root.removeEventListener('click',click);narrow.removeEventListener('change',resize);root.replaceChildren();root.classList.remove('cvs-app');}});
}
